### PR TITLE
Adding detailed information about license removal to delete-or-restore-mailboxes.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2667.

I tested it, but @Benny-54, could you kindly confirm it with the product team? Thanks!

More info:
https://techcommunity.microsoft.com/t5/exchange-team-blog/change-in-behavior-for-delicensed-exchange-online-users/ba-p/605962
I think this behaviour was never finally changed as it was originally planned.

### CODE REVIEW

**Comment by Benny-54** [comment]
Hi @dariomws please check with aditya.mukund@microsoft.com for confirmation, thank you!

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dariomws** [comment]
It's an important addition, and I want to confirm this behaviour. @get-itips could you kindly test it? Thanks!

**Comment by dariomws** [comment]
@Swatyario could you kindly help to confirm this information? Thanks!

**Comment by Swatyario** [comment]
Adding @Joanne ***@***.***> here.


Thanks and kind regards,

Aditya Mukund
Program Manager
EAC & EXO Manageability
Stay safe, stay healthy, stay fit!
________________________________

**Comment by get-itips** [comment]
> It's an important addition, and I want to confirm this behaviour. @get-itips could you kindly test it? Thanks!

I could test and verify what you say in the issue comments: "_You cannot search it using Get-Mailbox or restore it using Undo-SoftDeletedMailbox. You need to reassign the license._"

I was able to get access again to the mailbox if re-assigning the license.

**Comment by dariomws** [comment]
Thanks @get-itips!

**Pull request merged**
