### PR TITLE
Initial-draft-modern-exchange-admin-center

### PR DESCRIPTION
**Pull request by Benny-54**
Initial draft for the Modern EAC. Task 4393085.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — COMMENTED** [review]
I really don't know what this is about. Please clarify.

**Comment by Benny-54** [comment]
Its a draft in progress, kindly don't review it for now. I have to update it with images and some details.

**Comment by Benny-54** [comment]
Kindly don't merge this PR, as the images are yet to be added and reviewed. Thank you.

**Pull request closed without merging**
