### PR TITLE
Update safety-net.md

### PR DESCRIPTION
**Pull request by przlplx**
Approved in CSS content triage - Content Idea Request 103637: New section added between "How Safety Net works" and "Message resubmission from Safety Net": "Safety Net maximum supported sizes"

### CODE REVIEW

**Comment by TobyTu** [comment]
@msdmaguire I see the article still not update, should we need to wait for more time?

**Comment by msdmaguire** [comment]
@TobyTu looks like the branch wasn't merged with live (published). I am merging now so you should see the new section in 12-24 hours.

**Comment by przlplx** [comment]
Thank you for your help, David! I see the new content published live.

Unfortunately, I realize only now that I had introduced an error in the new text. I have corrected the text and submitted a new pull request:

https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1154

Could you please help to approve the correction and get it published?

Thanks!
-Jerry
Content Developer
CSS Content Experience
v-jesits@microsoft.com<mailto:v-jesits@microsoft.com>
[cid:image003.jpg@01D53B2C.74AEA4E0]

**Comment by msdmaguire** [comment]
Merged. Fix should go live by end of week.

**Comment by przlplx** [comment]
Excellent! Thank you, again, for the help!

**Pull request merged**
