### PR TITLE
Delete

### PR DESCRIPTION
**Pull request by djdavegriff**
Delete this info

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by chrisda** [comment]
@djdavegriff, thanks for the update, but you need to sign the license agreement.

**Comment by scanum** [comment]
@djdavegriff hi could you please sign the cla? In order for us to be able to merge this PR and implement your updates? Thanks

**Comment by scanum** [comment]
@djdavegriff hi could you please sign the cla? In order for us to be able to merge this PR and implement your updates? Thanks

**Comment by nenonix** [comment]
@scanum am not sure the process for deleting a page was followed in this case.

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by chrisda** [comment]
I'm closing this PR due to inactivity. The request was to delete an entire topic, which has other steps (redirects) that need to be done.

**Pull request closed without merging**
