### PR TITLE
Fix source side validation script file name

### PR DESCRIPTION
**Pull request by bill-long**
The public folder source-side validation script used to be named ssv.ps1, but is now named SourceSideValidations.ps1. This PR updates the name in the docs.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@mattpennathe3rd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by mattpennathe3rd** [comment]
@bill-long Thank you very much for updating this. The change will be merged shortly and the updated article should be published later today. Thanks for helping us improve the docs.

**Comment by mattpennathe3rd** [comment]
@bill-long The file name was also out of date in another article, so I have updated that one, as well. Thanks again for pointing this out.

**Pull request closed without merging**
