### PR TITLE
Dariomws patch 4

### PR DESCRIPTION
**Pull request by dariomws306**
I have added Exchange 2019 to hybrid-deployment-prerequisites.md and Windows 10 to fix-outlook-connection-problems-in-office-365.md.

Finally, I didn't make changes to exchange-server-supportability-matrix-exchange-2013-help.md on this PR.

Thanks.

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@dariomws306 There is a conflict with this PR. Please fix this so I can have it reviewed and merged.

**Comment by dariomws306** [comment]
@AndreaBarr , fixed, thank you!

**Comment by AndreaBarr** [comment]
@dstrome Can I merge this?

**Comment by kenwith** [comment]
I 'think' it is OK but lets wait for one of the Exchange writers to confirm, @dstrome , @chrisda , or @msdmaguire

**Comment by chrisda** [comment]
Sorry, the branch was out of date and it took to long to update. Considering the source, yes, this PR is OK to merge. The parameters in question didn't have descriptions, anyway.

**Comment by kenwith** [comment]
@dariomws306 - I saw you just deleted it.. would you resubmit a PR?

**Comment by dariomws306** [comment]
@kenwith , sure!

**Comment by kenwith** [comment]
Do you have to resubmit the PR? Chris in my office and we were just talking about it, thanks for this!

**Comment by dariomws306** [comment]
New PR: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/473

**Pull request merged**
