### PR TITLE
Update docfx.jso

### PR DESCRIPTION
**Pull request by Ghaethliii**
https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

### CODE REVIEW

**Comment by Ghaethliii** [comment]
https://github. com/googleads/googleads-mobile-android mediation/blob/f23b1a236d4b59d84d5f4ccc09d158f4cc09d15879364139363cwbertinG.

**Comment by traya1** [comment]
Closing PR. We do not accept public contributions to this file.

**Comment by Ghaethliii** [comment]
> https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

**Comment by Ghaethliii** [comment]
https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

**Comment by Ghaethliii** [comment]
``

**Review by Ghaethliii — COMMENTED** [review]
https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

**Review by Ghaethliii — COMMENTED** [review]
> `
https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md`

**Pull request closed without merging**
