### PR TITLE
.NET matrix fixed

### PR DESCRIPTION
**Pull request by lusassl-msft**
-Exchange 2016 CU11/12 don’t support 4.8
-Exchange 2013 CU23 support 4.7.2 (required)

### CODE REVIEW

**Comment by lusassl-msft** [comment]
@chrisda @scanum please check

**Comment by lusassl-msft** [comment]
@chrisda Hi Chris, https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019 still shows the wrong .NET matrix. Public branch seems to be fine now (https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md). Is there a way to speed up docs article refresh?

**Comment by chrisda** [comment]
@lusassl-msft, it looks like my PR from Master to Live from Friday was stuck. I closed it and opened another. I'll babysit it until it goes through.

**Comment by lusassl-msft** [comment]
Docs is now up to date. Thanks Chris

**Pull request merged**
