### PR TITLE
Update view-statistics.md

### PR DESCRIPTION
**Pull request by heathca**
'LastAccessedTime' is only available for on premises versions of Exchange and not available for Exchange Online.

### CODE REVIEW

**Comment by mattpennathe3rd** [comment]
@heathca Thank you for the PR, but we generally do not call out differences between Exchange Online and Exchange on-prem in the docs. There are countless differences between the products and the documentation sets are separated in the navigation.

**Comment by heathca** [comment]
The reason that the edit was put in was because we had a case on it and product engineering requested that we update the documentation.

Thank you for choosing Microsoft!


Heather Campbell

Support Escalation Engineer - Exchange
Customer Service & Support
Office:   425.538.5415
Office Hours: 7am-4pm Pacific
heathca@microsoft.com<mailto:heathca@microsoft.com>
Meeting and exceeding your expectations are my top priorities. We are interested in any feedback you might have about the service that you received on this incident. My manager, Jeff Peters, can be contacted through email at JeffPete@microsoft.com<mailto:JeffPete@microsoft.com>  or by telephone at (425) 706-6129. 24x7 Support Lines: Premier Support (800) 936-3100, U.S. National Support (800) 936-3200.

**Comment by mattpennathe3rd** [comment]
@heathca Thanks for clarifying! I double checked and this addition is good to go. It will be published in the near future.

**Comment by heathca** [comment]
Thank you!


Thanks,
Heather Campbell

**Pull request merged**
