### PR TITLE
Create remote-domains.md

### PR DESCRIPTION
**Pull request by ChandraKavya**

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@ChandraKavya @chrisda @SerdarSoysal Hi! Changes look correct. Could you please confirm and merge? Thanks!

**Comment by ChandraKavya** [comment]
Hi,

I am not aware of how merging can be done? Can once you please explain and I can take care of it.

Thanks,
Kavya

**Comment by chrisda** [comment]
@ChandraKavya, no worries. Only people like me with Write access to the repo can merge Pull Requests. I have meeting scheduled tomorrow (Th 5/16) to discuss this and your other change requests. I'll likely merge after that.

**Comment by ChandraKavya** [comment]
Thanks Chris 😊

**Pull request merged**
