### PR TITLE
Fixed url typo in customize-and-schedule-mail-protection-reports.md

### PR DESCRIPTION
**Pull request by dariomws**

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tiburd** [comment]
@dariomws - When I select the **Files changed 1** tab, I see this:
image

**Comment by dariomws** [comment]
@tiburd interesting...

This is why this update was applied in another PR authored by me:
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/2763

**Pull request closed without merging**
