### PR TITLE
Fix formatting in "Update disable-enable-voicemail-missed-call-notifications.md"

### PR DESCRIPTION
**Pull request by cabailey**
Reviewer - I can't see the TOC for this article on the public site.  Might be just timing issue but please check.
@Tangela123 FYI

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by cabailey** [comment]
I still don't see the TOC on the live site?  https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/disable-enable-voicemail-missed-call-notifications

**Comment by Tangela123** [comment]
@Kateyanne  - How long will it take for these changes to show up in the TOC?

**Comment by Kateyanne** [comment]
~ adding Andre and Manuela

Has the file been added to the TOC.md?

I’ve looked into this, and this is what I’ve been told: I found the part of the Exchange TOC that it should be in and I don’t see that topic there. It should be one of the topics under Journaling and it’s not. So my same advice still stands. The author should add the topic to the Exchange Online TOC, and if they say it’s already there, or they do that and it doesn’t work, contact Ask an Admin (Kateyanne can do this.).

I believe the topic needs to be added here: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/onlinetoc/toc.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-Exchange%2Fblob%2Fpublic%2FExchange%2FExchangeOnline%2Fonlinetoc%2Ftoc.md&data=02%7C01%7Cv-kaunu%40microsoft.com%7Cede7e1c2985e4ff7a44508d85c22986e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637360652147266357&sdata=prwSyk9AXhkLdmefWJu0tphXBRU8o9OnsLugf1sePnY%3D&reserved=0> (but I’m not 100 sure).

Normally something gets “into” a TOC.md file by being added to it by the author or someone else. This usually happens when the article is new.

I can see that TOC online when I go to the Outlook “Journaling” content (https://docs.microsoft.com/en-us/Exchange/security-and-compliance/journaling/journaling<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2FExchange%2Fsecurity-and-compliance%2Fjournaling%2Fjournaling&data=02%7C01%7Cv-kaunu%40microsoft.com%7C55ef375354204829501208d85c213790%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637360645023465834&sdata=rfWzhzQrFvah4Amm7EZT9aOinurOeIWT5hQBo0CZrDs%3D&reserved=0>) but I don’t see it when I click on this page: https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/disable-enable-voicemail-missed-call-notifications

**Comment by Kateyanne** [comment]
@cabailey @tangela123 TOC is now on the live site.  https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/disable-enable-voicemail-missed-call-notifications

**Pull request merged**
