### PR TITLE
fix link

### PR DESCRIPTION
**Pull request by get-itips**
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2757

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tiburd** [comment]
@get-itips - Hi, Andres - I'm not seeing any changes in this PR. When I select the **Files changed 1** tab, it says that no files are selected:

> 
image

Can you please advise how I can view the change(s)?

Thank you!

**Comment by get-itips** [comment]
@tiburd super weird 😆 and the PR is not required anymore it seems, closing.

**Pull request closed without merging**
