### PR TITLE
Adding more info

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2671
@dariomws can you kindly review and give me your opinion? Thank you

### CODE REVIEW

**Review by dariomws — COMMENTED** [review]
I think that this important note is talking about Google Workspace, not Microsoft 365. So that link is misleading.
At least that is what I understand reading the paragraph above the note and the note itself:

"The MX record for the primary domain "fabrikaminc.net" still points to Google Workspace. Now that User 1 and User 2 have been fully migrated to Microsoft 365 or Office 365, they should start working out of Microsoft 365 or Office 365. On the Google Workspace side, automatic mail forwarding has been set up for migrated users, so that new emails sent to their Google Workspace address will be delivered instead to the Microsoft 365 or Office 365 address via the routing domain. This is shown by the green arrows in the above diagram.

> [!IMPORTANT]
> If your organization has disabled a user's ability to set a forwarding address, the Google Workspace migration tool will also be unable to set the forwarding address. You must enable permissions to set SMTP forwarding in order for forwarding to be set successfully during your migration."

Additionally, not sure about this setting. For me is strange that nobody has reported it before. I never experienced it. We need to test it, I think it's a simple forwarding to an external address.

**Comment by get-itips** [comment]
Good point about the note talking about Google Workspace specific.


I just saw this in the article that I think already covers this situation

> you should check that mail flow will work from Office 365 to Google Workspace. Be sure that either your default Remote Domain ("*") has Automatic Forwarding enabled, or that there is a new Remote Domain for your Google Workspace routing domain (e.g. "gsuite.fabrikaminc.net") that has Automatic Forwarding enabled.

What do you think?

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by get-itips** [comment]
> @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

Give me some more time, it's still draft :)

**Comment by dariomws** [comment]
@get-itips agree. I think that note cover it.

**Comment by get-itips** [comment]
Closing this PR.

**Pull request closed without merging**
