### PR TITLE
[Hold] Updated Summary Removing 2016 and 2019 and adding 2013.

### PR DESCRIPTION
**Pull request by j0rt3g4**

### CODE REVIEW

**Comment by j0rt3g4** [comment]
Updated information on the summary.
@JohanFreelancer9  @nenonix  this one would need a review. Thank you in advantage

**Comment by scanum** [comment]
@mattpennathe3rd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by chrisda** [comment]
I'm looking into this. While it's true that steps 4, 7, and 12 are only available in Exchange 2013, we can't simply turn this into a 2013 topic because:

- It's in the Exchange 2016/2019 content area.
- There's already an Exchange 2013 version of the topic: <https://docs.microsoft.com/Exchange/clean-up-the-recoverable-items-folder-exchange-2013-help>

I'm trying to find out if there's a way (or a need) in Exchange 2016/2019 to disable the MFA. You configure the MFA work cycle as described [here], but you must specify a number of days. You can specify a lot of days (for example, 18,250 or 50 years), but I'm not sure if that's good enough.

**Comment by chrisda** [comment]
It seems that the alternative to turning off the MFA within Exchange is to stop the Microsoft Exchange Mailbox Assistants (MSExchangeMailboxAssistants) service on the server, so I updated the topic accordingly in a different PR.

Therefore, closing.

**Pull request closed without merging**
