### PR TITLE
Added Note

### PR DESCRIPTION
**Pull request by mukeshHCW**
Just a note addition to help users navigate for help regarding DOD or GCC High

### CODE REVIEW

**Comment by mukeshHCW** [comment]
proposed by Ian LIu

**Comment by mattpennathe3rd** [comment]
@mukeshHCW Thanks for opening these pull requests, but I need a bit more background information before I can approve these.

We do not mention this parameter anywhere in our Exchange documentation, so it is not clear what is "different" about it when used in the context of a GCC environment. Can you (or someone else who can provide background information) either update these PRs with more details or contact me internally to explain?

**Comment by mukeshHCW** [comment]
Hi Matt,

I am PM for Hybrid Exchange (my alias: mukkum). There is a recent request from Ian Liu with regards to Set-Federation Command.
This change is necessitated by lot of customer issues that are occurring because of a recent change that happened.
When ITAR customers call the following command, 
‘New-FederationTrust -Name "Microsoft Federation Gateway" –Thumbprint <thumbprint>’

The default setting is coming from MD2. Since we don’t have specific MD2 Arlington instance, the scenario will break for ITAR tenants. The only walkaround is for customer to modify the “Microsoft Federation Gateway” federation trust directly to point to ESTS Arlington. 

Above error can lead customers to these sections, so a note here would help them to navigate to right documentation.

@mattpennathe3rd do share your microsoft email id as well, so that i can send mail directly and loop in necessary people if required. 

Thanks
Mukesh Kumar

**Comment by mukeshHCW** [comment]
@mattpennathe3rd Is something pending on me here?

**Pull request closed without merging**
