### PR TITLE
creating legacy authentication policies

### PR DESCRIPTION
**Pull request by rdiazel**
This document provides complete guiding on how to create a policy to disable legacy authentication and full working PowerShell scripts to achieve it

### CODE REVIEW

**Comment by rdiazel** [comment]
Hi Ken,

I created this based on the document https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online?redirectSourcePath=%252fen-ie%252farticle%252fDisable-Basic-authentication-in-Exchange-Online-bba2059a-7242-41d0-bb3f-baaf7ec1abd7

It provides additional information and fully functional commands to easily achieve this task.

It needs a writer to edit and give format to the document. I may say that the link to that document could be included as a link in the document above if possible.



Best Regards

Ricardo Diaz
Azure Support Engineer
Office: 855-4252648 x60477
ridia@microsoft.com<mailto:ridia@microsoft.com>
Wed-Sat 8-7pm CST

Technical Support Manager: Erneth Castro  Erneth.Castro@microsoft.com<mailto:Erneth.Castro@microsoft.com>

[Microsoft Logo]
P Please consider the environment before printing this email.

**Comment by kenwith** [comment]
@rdiazel - I am going to close this one for now, I see you are in support org.. can you email me and I will work with you and the others to figure out how to get this published.. this is new territory so thanks for your patience and thanks for putting the efforts on this!  My alias is    kenwith

**Comment by kenwith** [comment]
@rdiazel - what I often do is look at other articles that are similar to see how the author used the Markdown.. here is one example: https://raw.githubusercontent.com/MicrosoftDocs/OfficeDocs-Exchange/public/Exchange/ExchangeServer/collaboration/shared-mailboxes/create-shared-mailboxes.md

**Comment by rdiazel** [comment]
ok is fine. it is up to you if you consider this needs to be published or not. in any case the format is already here in case that you want to included https://github.com/rdiazel/identity/blob/master/disable%20legacy%20authentication%20in%20EXO

**Comment by kenwith** [comment]
It needs to be in Markdown though so it can render properly.

**Comment by AndreaBarr** [comment]
@dstrome Can I merge this?

**Comment by dstrome** [comment]
hi @rdiazel ,

Thanks very much for submitting this topic, however, there is already a topic on disabling basic authentication here - https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online - that appears to cover the majority of the same steps. Rather than create a new topic, please update the existing topic with any scenarios you feel are missing and we'll incorporate them into that topic.

Thanks!
David.

**Pull request closed without merging**
