### PR TITLE
Update in-place-archiving.md

### PR DESCRIPTION
**Pull request by viktgin**
Hi all, 
Recently we discuss that statement "     > [!IMPORTANT]
    > Locating a user's mailbox and archive on different versions of Exchange Server isn't supported" in our internal DL list and agreed it's a really odd statement given we support 2010 on-premises users having EOA. That probably, goes back to the days when 2007 was still in support and could coexist with 2010 or 2013 which supported archives. Having this statement officially published cause  a lot of concearn, especially in 2013/2016 co-existens. I would suggest to remove that statementor event state that it's fully supported. Thanks.

### CODE REVIEW

**Comment by scanum** [comment]
@SerdarSoysal Changes look correct, can this be merged?

**Comment by viktgin** [comment]
Hi all!
Should we wait when public article will be updated? As original article still contain statement that different versions of exchange for mailbox and archive are not supported. https://docs.microsoft.com/en-us/exchange/policy-and-compliance/in-place-archiving/in-place-archiving?view=exchserver-2019
Thanks!

**Comment by chrisda** [comment]
@viktgin, the offending statement was removed a couple of days ago. Can you confirm?

**Comment by viktgin** [comment]
> @viktgin, the offending statement was removed a couple of days ago. Can you confirm?
Yes, now I see it. Looks like it takes some times to be updated. Thanks to you!

**Pull request merged**
