### PR TITLE
Update collaboration-exo.md

### PR DESCRIPTION
**Pull request by guruxp**
Adding a fixed number to define what is a small number. This will help customer plan better the use of one solution or another and also support will benefit from this so can provide a public article about it.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by guruxp** [comment]
@scanum @JohanFreelancer9 any update on when this will go live?

**Comment by JohanFreelancer9** [comment]
@scanum

**Comment by scanum** [comment]
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
