### PR TITLE
Update create Mail User from EAC manage-mail-users.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1528

It looks like it was a copy and pastes of the on-premises article.

### CODE REVIEW

**Comment by mattpennathe3rd** [comment]
@dariomws I will not be able to review this in depth for some time, but does this new procedure match the interface of the new EAC or the classic EAC? (Classic was very recently retired.)

**Comment by dariomws** [comment]
Hi @mattpennathe3rd,

It matches the interface of the classic EAC:
image

Is it retired? I understand that the new Modern Exchange Admin Center is still in preview and you can only access it from https://admin.exchange.microsoft.com/:
image

**Comment by mattpennathe3rd** [comment]
@dariomws Classic entered rolling retirement in early March and access to it is already disabled for many organizations. Everything in this repo will eventually need to be re-documented for use with the new admin center and no new documentation should reflect the classic admin center; it will be gone very soon.

**Comment by mattpennathe3rd** [comment]
@dariomws I removed my prior comment because it turns out I was wrong; I confused the EAC with the M365 admin center, which is in active retirement. Apologies for that! We have several branding and technology transitions/retirements overlapping right now and it's sometimes difficult to keep them all straight.

Current plan is that the classic EAC will be available into 2021, from what I am told.

**Comment by dariomws** [comment]
Thank you @mattpennathe3rd! I thought that I missed something. So, the new Modern Exchange Admin Center will be available into 2012. Thanks again!

**Comment by mattpennathe3rd** [comment]
@dariomws The classic and modern EAC are available now for many customers, side by side; customers can switch between them. The modern EAC is gradually being rolled out to everyone, but eventually (sometime in 2021), the classic EAC will be retired and removed, leaving the modern EAC as the only option. At least, this is the current plan.

**Pull request closed without merging**
