### PR TITLE
Added O365 permissions in EXO article to exchange-admin-center.md

### PR DESCRIPTION
**Pull request by dariomws**
Also, updated/fixed "Office 365 permissions in Exchange Online" table.

https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1922

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@mattpennathe3rd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by chrisda** [comment]
@dariomws, I'm sorry, but I had no idea this PR was sitting here, and I added the same (or similar) information based on a completely separate M365 security issue.

So, closing.

**Comment by dariomws** [comment]
Don´t worry and thanks @chrisda.

@scanum, I think we can close https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1922.

**Pull request closed without merging**
