### PR TITLE
Include common URLs in hybrid-deployment-prerequisites.md

### PR DESCRIPTION
**Pull request by dariomws**
Related to https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/2618.

@felgar73 @get-itips for your reference.

@chrisda, could you kindly review it and let us know your thoughts? I think we had a discussion about this information some months ago.

Thank you everyone!

### CODE REVIEW

**Comment by get-itips** [comment]
👍

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
