### PR TITLE
chore: Reflow README headings

### PR DESCRIPTION
**Pull request by nschonni**
Alternately the middle section could be moved to a CONTRIBUTING.md

### CODE REVIEW

**Comment by kenwith** [comment]
@nschonni - this looks good and easier to read and better flow. I originally created the README on the PowerShell repo and then copy/pasted over here. Interested to work on the original as well? :D  https://github.com/MicrosoftDocs/office-docs-powershell

**Comment by nschonni** [comment]
Sure, I'll pull parts out to a CONTRIBUTING.md and if that all looks good here I'll do the same there

**Comment by nschonni** [comment]
@kenwith does the README/CONTRIBUTING split in https://github.com/MicrosoftDocs/visualstudio-docs make sense?

**Comment by kenwith** [comment]
@nschonni - wow really cool with the contributing guide idea.. it might have to be edited but love the idea. Let me also loop in @chrisda for feedback. Chris - what do you think about splitting out a CONTRIBUTING.md guide like how visualstudio-docs did it and we can use that through the Office commercial repos?

**Comment by chrisda** [comment]
@kenwith, yes, I like the idea of splitting out.

**Pull request merged**
