### PR TITLE
Update client-access-rules.md

### PR DESCRIPTION
**Pull request by kellybos**
Removed this note - 
> [!NOTE]
> Microsoft sync technology that's used in Outlook for iOS and Android and Windows Mail isn't available in Client Access Rules.

Client Access Rules can be used to block Windows Mail App using the UniversalOutlook protocol. ActiveSync device access rules can be used to block for Outlook for mobile.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tiburd** [comment]
@kellybos 
Hi, Kelly,
This pull request was opened in the public repo. PMs and content developers should work in the private repo, as described in [the authoring guide](https://review.docs.microsoft.com/en-us/office-authoring-guide/office-docs-authoring-overview?branch=main). We reviewed and merged this PR but encourage you to use the private repo for future contributions to Microsoft Docs.
Thanks!

**Pull request merged**
