### PR TITLE
fix video tag

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2954

### CODE REVIEW

**Comment by get-itips** [comment]
@tiburd

**Comment by scanum** [comment]
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

**Comment by tiburd** [comment]
reviewed + confirmed before merging

**Comment by rabbyn** [comment]
From my end the video link of this page is still not correct , see https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/policy-tips

**Pull request merged**
