### PR TITLE
issue #623

### PR DESCRIPTION
**Pull request by j0rt3g4**
Issue #623 
PR #905
It was made from branch #Issue 622

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@SerdarSoysal Hi changes look correct. Could you please confirm and merge? Thanks!!

**Comment by scanum** [comment]
@chrisda Hi Chris, could you please look at this PR confirm and merge if correct? Thanks!

**Comment by scanum** [comment]
@chrisda Any updates on this?  PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@chrisda Any updates on this? PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by baardhermansen** [comment]
@scanum  @chrisda Hi! Shouldn't this PR have been pulled into public, not the other way round (like was done in august)?

**Comment by scanum** [comment]
@chrisda Hi Chris, any updates on this PR? Thanks!

**Comment by scanum** [comment]
@chrisda Hi Chris, any updates on this? Thanks!

**Pull request merged**
