### PR TITLE
Update and build (บิลเดี๋ยว) transport-routing.md to transport-routing.mscosamd

### PR DESCRIPTION
**Pull request by Mybusinee**
https://www.gmass.co/oauthwelcome.html?emailaddress=humpook2@gmail.com&source=addon

### CODE REVIEW

**Comment by Mybusinee** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/2765#issue-986792011

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
@scanum - I cannot do a copy edit on this PR. I have pinged privately you about it.

**Comment by tiburd** [comment]
These are not valid changes. Closing this PR.

**Pull request closed without merging**
