### PR TITLE
UCMA 4.0 is not supported on newer OS or .net 4.8

### PR DESCRIPTION
**Pull request by Karl-WE**
As per download description and requirements UCMA 4.0 is not supported on any OS that would qualify the requirements of Exchange 2016 or 2019 or later, nor is it compatible for .net 4.8.

references: 
https://github.com/microsoft/CSS-Exchange/issues/535
https://docs.microsoft.com/en-us/answers/questions/167684/exchange-2016-exchange-2019-wrong-recommendations.html

If you intend to double check this please correct the odd C++ Redist check in the UCMA installer 6.0 from 
= 2015-2019 C++ Redists x64 / x86 version to >= 2015-2019 C++ Redists x64 / x86.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by Karl-WE** [comment]
@scanum @JohanFreelancer9 hi there despite your signoff the changed are not yet there at docs. Ideas?

**Comment by scanum** [comment]
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
Hi @Karl-WE we need to get the PR approved and merged by the Microsoft team. Thanks for your patience.

**Comment by Karl-WE** [comment]
Oh I see for me it looked like merge. Just checking back as some months ago there was a problem with the Pipeline not pushing changes from merged to public docs. So I double check all merges after some time.
@scanum

**Comment by tiburd** [comment]
@Karl-WE - The Exchange team noticed your change and asked me to revert it:

> AFAIK the 6.0 version was not yet tested with Exchange so I'd strongly recommend reverting the change.
> We` still ship UCMA 4.0 by default with Exchange 2019 and our testing is done by using UCMA 4.0.

It was reverted in [this PR](https://github.com/MicrosoftDocs/OfficeDocs-Exchange-pr/pull/2070), and a note has been added that states UCMA 4.0 must be used even if the documentation for UCMA 4.0 stated that it's not supported with Windows server 2016/2019.

**Comment by Karl-WE** [comment]
Thank you Tina @tiburd. I think I will bury this topic altogether. It is not work the hassle. Of course they would need to test it, there are some hardcoded checks and still some error messages according to docs pointing to this.

**Comment by lusassl-msft** [comment]
@Batre-MSFT we currently use the following statement: 

_"Make sure to use the Unified Communications Managed API 4.0 until something else is communicated by the Exchange team.
When installing on Windows Server Core, you must use the installation package located in \UCMARedist on distributed media."_

The ask from @Karl-WE is to add the following sentence:
_"It is known that UCMA 4.0 is listed as unsupported for Windows Server 2016 and later, and .net 4.7 or later."_

**Pull request merged**
