### PR TITLE
Add missing procedure

### PR DESCRIPTION
**Pull request by hishikitetsuya**
Recreating step for _SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9}_ is missing. This request proposes adding `Enable-Mailbox` as well as `Set-Mailbox -UMDatastorage:$true` since the mailbox should have _OrganizationCapabilityUMDataStorage_ capabilities.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tiburd** [comment]
@get-itips @dariomws @tseward 
Hi! Because this is a PowerShell code block, please review.
Last reviewer: please @ mention me so that I can merge the PR.
Thank you!

**Review by get-itips — APPROVED** [review]
I see that what you are adding is present in 2016 and 2019 version articles.

**Review by dariomws — COMMENTED** [review]
@hishikitetsuya, are you sure about this update?

There is another article that does not have them:
https://docs.microsoft.com/exchange/delete-and-re-create-default-discovery-mailbox-exchange-2013-help

**Comment by hishikitetsuya** [comment]
@dariomws I don't quite understand your point. The Discovery mailbox you mentioned and the arbitration mailbox _SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9}_ are totally different. Those two mailboxes are created separately within Exchange installation, and thus recreating steps should also be separated. 

Also, note that we have the correct steps in [Exchange 2016/2019](https://docs.microsoft.com/en-us/exchange/architecture/mailbox-servers/recreate-arbitration-mailboxes?view=exchserver-2019).

**Review by dariomws — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by scanum** [comment]
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
