### PR TITLE
[Hold] Remove the landing page metadata

### PR DESCRIPTION
**Pull request by docs-product**
The current landing page layout is going away, and we need to make sure that no existing pages are using it.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@docs-product PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by docs-product** [comment]
I see that this is already covered by https://github.com/MicrosoftDocs/OfficeDocs-Exchange-pr/pull/1095, so this should no longer be necessary.

**Comment by docs-product** [comment]
@mattpennathe3rd can you please merge this PR? Thank you!

**Comment by mattpennathe3rd** [comment]
@docs-product Is this safe to merge? Investigation of this when applied to certain pages in this repo resulted in serious breakage of the page. I was told that someone would be in touch to discuss further changes that were needed. Please contact me internally.

**Comment by msdmaguire** [comment]
This page has been updated in a separate PR, and if that's not the case, the issue will resurface and I can take a closer look then.

**Pull request closed without merging**
