### PR TITLE
Delete exchange-online-and-exchange-online-protection-service-upgrade.md

### PR DESCRIPTION
**Pull request by dariomws306**
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/991

### CODE REVIEW

**Comment by chrisda** [comment]
@dariomws306, why are we deleting this and do we need a redirect configure so people don't get 404's from old links?

**Comment by dariomws306** [comment]
Because they have information about the difference between FOPE and EOP. They are old and I couldn't find other to replace them.

Do you know if these articles exist?

**Comment by scanum** [comment]
@chrisda Following up on this PR. Thanks!

**Comment by chrisda** [comment]
You can't just delete an existing topic without a corresponding redirect, because that will result in 404 errors. Now that I created the redirect (PR #733), we can delete the topic.

**Comment by dariomws306** [comment]
Thanks @chrisda!!

**Pull request merged**
