### PR TITLE
Remove sentence from hybrid-with-multiple-forests.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2696.

For instance: https://docs.microsoft.com/azure/active-directory/hybrid/plan-connect-topologies#multiple-forests-multiple-sync-servers-to-one-azure-ad-tenant:
"Having more than one Azure AD Connect sync server connected to a single Azure AD tenant is not supported. The exception is the use of a staging server."

@Benny-54 Could you kindly share a name to confirm this removal? Thanks!

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by Benny-54** [comment]
@dariomws please check with Aditya.Mukund@microsoft.com, thank you.

**Comment by dariomws** [comment]
@JoanneHendrickson @Swatyario maybe you kindly confirm this information. Thanks!

**Comment by Swatyario** [comment]
Adding @Mukesh ***@***.***> for further help as the doc link is related to Exchange Hybrid.


Thanks and kind regards,

Aditya Mukund
Program Manager
EAC & EXO Manageability
Stay safe, stay healthy, stay fit!
________________________________

**Comment by mukeshHCW** [comment]
The changes are okay, nothing confrontational. Feel free to update this.

**Comment by scanum** [comment]
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
