### PR TITLE
Update message-format-and-transmission.md

### PR DESCRIPTION
**Pull request by guruxp**
Updating documentation to include RTF combined with S/MIME will suffer from conversion issues from our side. PG already stated this won't be fixed and the solution is to rely on html format instead.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by guruxp** [comment]
@scanum I see @JohanFreelancer9 approved the changes, I believer the only thing left is merging? :)

**Comment by scanum** [comment]
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tiburd** [comment]
@guruxp 
Hi, Alberto,
This pull request was opened in the public repo. PMs and content developers should work in the private repo, as described in [the authoring guide](https://review.docs.microsoft.com/en-us/office-authoring-guide/office-docs-authoring-overview?branch=main). We reviewed and merged this PR but encourage you to use the private repo for future contributions to Microsoft Docs.
Thanks!

**Pull request merged**
